name: example
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  ioc_container:
    path: ../
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  retry: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

dependency_overrides:
  collection: ^1.17.0

flutter:
  uses-material-design: true
