name: ioc_container
description: A Dart Ioc Container. Store and manage dependencies in one place keyed by type. It simplifies creating instances of your classes.
version: 0.7.0
homepage: https://github.com/MelbourneDeveloper/ioc_container

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  dart_code_metrics: ^4.17.1
  lints: ^2.0.0
  test: ^1.16.0
