name: ioc_container
description: A sample command-line application.
version: 0.1.0
homepage: https://github.com/MelbourneDeveloper/ioc_container

environment:
  sdk: ">=2.17.0 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
