name: ioc_container
description: A lightweight, flexible, and high-performance dependency injection and service location library for Dart and Flutter
version: 1.0.12
repository: https://github.com/MelbourneDeveloper/ioc_container

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  austerity:
    path: ../austerity
  dart_code_metrics: ^4.20.0
  lints: ^2.0.0
  meta: ^1.7.0
  test: ^1.16.0
