name: ioc_container
description: A Dart Ioc Container. Store and manage dependencies in one place keyed by type. It simplifies creating instances of your classes.
version: 1.0.7
repository: https://github.com/MelbourneDeveloper/ioc_container

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ">=2.0.0 <6.0.0"
  build: ^2.3.1
  build_config: ^1.1.0

dev_dependencies:
  austerity: ^0.0.9-beta
  build_runner: ^2.3.2
  dart_code_metrics: ^5.1.0
  lints: ^2.0.0
  meta: ^1.7.0
  source_gen: ^1.2.3
  test: ^1.16.0
