include: package:austerity/analysis_options.yaml

analyzer:
    errors:
        unused_local_variable: ignore

dart_code_metrics:
  anti-patterns:
    - long-method:
        severity: error
    - long-parameter-list:
        severity: error
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
    weight-of-class: 0.33
    halstead-volume: 150
  metrics-exclude:
  rules:
    - newline-before-return:
        severity: error
    - no-boolean-literal-compare:
        severity: error
    - no-empty-block:
        severity: ignore
    - prefer-trailing-comma:
        severity: error
    - prefer-conditional-expressions:
        severity: error
    - no-equal-then-else:
        severity: error
    - avoid-restricted-imports:
        severity: error
    - avoid-global-state:
        severity: ignore
    - avoid-ignoring-return-values:
        severity: warning
    - avoid-late-keyword:
        severity: ignore
